// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type NewPost struct {
	UserID    string `json:"user_id"`
	Title     string `json:"title"`
	Caption   string `json:"caption"`
	IsPremium bool   `json:"isPremium"`
	IsVisible bool   `json:"isVisible"`
	Thumbnail string `json:"thumbnail"`
	Type      string `json:"type"`
	Media     string `json:"media"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

type NewWaitlist struct {
	Email string `json:"email"`
}

type Post struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Title     string    `json:"title"`
	Caption   string    `json:"caption"`
	IsPremium bool      `json:"isPremium"`
	IsVisible bool      `json:"isVisible"`
	Thumbnail string    `json:"thumbnail"`
	Type      string    `json:"type"`
	Media     string    `json:"media"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Query struct {
}

type Token struct {
	ID        string     `json:"id"`
	UserID    string     `json:"user_id"`
	Token     string     `json:"token"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

type UpdatePost struct {
	Title     string `json:"title"`
	Caption   string `json:"caption"`
	IsPremium bool   `json:"isPremium"`
	IsVisible bool   `json:"isVisible"`
	Thumbnail string `json:"thumbnail"`
	Type      string `json:"type"`
	Media     string `json:"media"`
}

type UpdateUser struct {
	Name             string     `json:"name"`
	Username         string     `json:"username"`
	Email            string     `json:"email"`
	Photo            *string    `json:"photo,omitempty"`
	StripeCustomerID string     `json:"stripe_customer_id"`
	IsActive         string     `json:"is_active"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
}

type User struct {
	ID               string     `json:"id"`
	Email            string     `json:"email"`
	Username         string     `json:"username"`
	Name             string     `json:"name"`
	Photo            *string    `json:"photo,omitempty"`
	StripeCustomerID string     `json:"stripe_customer_id"`
	IsActive         string     `json:"is_active"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
}

type Waitlist struct {
	ID        string     `json:"id"`
	Email     string     `json:"email"`
	CanEnter  bool       `json:"canEnter"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}
